#!/usr/bin/env zsh

# require eza, docker, mise, rustup
# aliasses
alias resource=". ~/.zshrc"
## ls
alias ls='eza --icons'
alias ll='eza --icons -lah'
alias llt='eza --icons -lah -T -L2'

## docker
alias dc="docker compose"
alias up="docker compose up -d && docker compose logs -f"
alias down="docker compose down"
alias logs="docker compose logs"


# PATH
export PATH="/opt/homebrew/opt/rustup/bin:$PATH"
eval "$(~/.local/bin/mise activate zsh)"

autoload -Uz compinit && compinit
# git
fpath=(~/.zsh $fpath)
source ~/.zsh/git-prompt.sh
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash

GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUPSTREAM=auto


setopt PROMPT_SUBST ; PS1='%F{green}%n@%m%f: %F{cyan}%~%f %F{red}$(__git_ps1 "(%s)")%f
\$ '